#!/usr/bin/env bash
# Generate a background color escape code based on tmux session name
# Uses high-contrast colors that work well on dark backgrounds

session_name=$(tmux display-message -p '#S' 2>/dev/null)

if [[ -z "$session_name" ]]; then
    echo "#[bg=cyan]"
    exit 0
fi

# Hash the session name and get a number 0-5
hash=$(echo -n "$session_name" | md5sum | cut -c1-2)
num=$((16#$hash % 6))

# High contrast colors (all work well with black text on dark bg)
# 0=cyan, 1=green, 2=yellow, 3=magenta, 4=red, 5=blue
case $num in
    0) color="#00d7d7" ;;  # cyan
    1) color="#00d700" ;;  # green
    2) color="#d7d700" ;;  # yellow
    3) color="#d75fd7" ;;  # magenta
    4) color="#ff5f5f" ;;  # red/coral
    5) color="#5f87ff" ;;  # blue
esac

echo "#[bg=$color]"
